services:
    web:
        build:
            context: backend
            dockerfile: ./backend/dockerfile
            target: build
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
