/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    mutation WorkoutCreateTemplate($input:WorkoutCreateTemplateInput!){\n        workoutCreateTemplate(input:$input){\n            workout {\n                id\n            }\n            errors {\n                message\n            }\n        }\n    }": typeof types.WorkoutCreateTemplateDocument,
    "\n    query GetWorkout($id: ID!) {\n        workout(id: $id) {\n            id\n            name\n            notes\n            exercises {\n                id\n                notes\n                movement {\n                    id\n                    name\n                    description\n                    primaryMuscleGroup\n                    equipmentType\n                    movementType\n                }\n                sets {\n                    id\n                    sequenceNumber\n                    completedReps\n                    minReps\n                    maxReps\n                    weight\n                    duration\n                    setType\n                }\n            }\n        }\n    }\n": typeof types.GetWorkoutDocument,
    "\n    mutation WorkoutCreateCompleted($input:WorkoutCreateCompletedInput!){\n        workoutCreateCompleted(input:$input){\n            workout {\n                id\n            }\n            errors {\n                message\n            }\n        }\n    }": typeof types.WorkoutCreateCompletedDocument,
    "\n    query weekInReview {\n        weekInReview {\n            message\n            totalWorkouts\n            totalVolume\n            topMuscleGroup\n            totalCardio\n            favoriteEquipment\n        }\n    }\n": typeof types.WeekInReviewDocument,
    "\n    query GetWorkouts($startMonth: Decimal, $startYear: Decimal) {\n        workouts(startMonth: $startMonth, startYear: $startYear, template: false) {\n            edges {\n                node {\n                    id\n                    startTime\n                    name\n                }\n            }\n        }\n    }\n": typeof types.GetWorkoutsDocument,
    "\n    query GetExercises($movementId: String, $after: String, $before: String, $count: Int) {\n        exercises(movementId: $movementId, after: $after, before: $before, first: $count) {\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n            edges {\n                node{\n                    id\n                    movement {\n                        name\n                        primaryMuscleGroup\n                        equipmentType\n                        movementType\n                    }\n                    workout {\n                        startTime\n                    }\n                    sets {\n                        id\n                        sequenceNumber\n                        completedReps\n                        weight\n                        duration\n                        oneRepMax\n                        volume\n                    }\n                }\n            }\n        }\n    }\n": typeof types.GetExercisesDocument,
    "\n    query GetMovements(\n        $after: String,\n        $name: String,\n        $count: Int,\n        $equipment: String,\n        $muscle: String) {\n            movements(\n                after: $after,\n                name_Icontains: $name,\n                first: $count,\n                equipmentType: $equipment,\n                primaryMuscleGroup: $muscle) {\n                    edges {\n                        cursor\n                        node {\n                            id\n                            name\n                            description\n                            primaryMuscleGroup\n                            equipmentType\n                            movementType\n                        }\n                    }\n            }\n    }\n": typeof types.GetMovementsDocument,
};
const documents: Documents = {
    "\n    mutation WorkoutCreateTemplate($input:WorkoutCreateTemplateInput!){\n        workoutCreateTemplate(input:$input){\n            workout {\n                id\n            }\n            errors {\n                message\n            }\n        }\n    }": types.WorkoutCreateTemplateDocument,
    "\n    query GetWorkout($id: ID!) {\n        workout(id: $id) {\n            id\n            name\n            notes\n            exercises {\n                id\n                notes\n                movement {\n                    id\n                    name\n                    description\n                    primaryMuscleGroup\n                    equipmentType\n                    movementType\n                }\n                sets {\n                    id\n                    sequenceNumber\n                    completedReps\n                    minReps\n                    maxReps\n                    weight\n                    duration\n                    setType\n                }\n            }\n        }\n    }\n": types.GetWorkoutDocument,
    "\n    mutation WorkoutCreateCompleted($input:WorkoutCreateCompletedInput!){\n        workoutCreateCompleted(input:$input){\n            workout {\n                id\n            }\n            errors {\n                message\n            }\n        }\n    }": types.WorkoutCreateCompletedDocument,
    "\n    query weekInReview {\n        weekInReview {\n            message\n            totalWorkouts\n            totalVolume\n            topMuscleGroup\n            totalCardio\n            favoriteEquipment\n        }\n    }\n": types.WeekInReviewDocument,
    "\n    query GetWorkouts($startMonth: Decimal, $startYear: Decimal) {\n        workouts(startMonth: $startMonth, startYear: $startYear, template: false) {\n            edges {\n                node {\n                    id\n                    startTime\n                    name\n                }\n            }\n        }\n    }\n": types.GetWorkoutsDocument,
    "\n    query GetExercises($movementId: String, $after: String, $before: String, $count: Int) {\n        exercises(movementId: $movementId, after: $after, before: $before, first: $count) {\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n            edges {\n                node{\n                    id\n                    movement {\n                        name\n                        primaryMuscleGroup\n                        equipmentType\n                        movementType\n                    }\n                    workout {\n                        startTime\n                    }\n                    sets {\n                        id\n                        sequenceNumber\n                        completedReps\n                        weight\n                        duration\n                        oneRepMax\n                        volume\n                    }\n                }\n            }\n        }\n    }\n": types.GetExercisesDocument,
    "\n    query GetMovements(\n        $after: String,\n        $name: String,\n        $count: Int,\n        $equipment: String,\n        $muscle: String) {\n            movements(\n                after: $after,\n                name_Icontains: $name,\n                first: $count,\n                equipmentType: $equipment,\n                primaryMuscleGroup: $muscle) {\n                    edges {\n                        cursor\n                        node {\n                            id\n                            name\n                            description\n                            primaryMuscleGroup\n                            equipmentType\n                            movementType\n                        }\n                    }\n            }\n    }\n": types.GetMovementsDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation WorkoutCreateTemplate($input:WorkoutCreateTemplateInput!){\n        workoutCreateTemplate(input:$input){\n            workout {\n                id\n            }\n            errors {\n                message\n            }\n        }\n    }"): (typeof documents)["\n    mutation WorkoutCreateTemplate($input:WorkoutCreateTemplateInput!){\n        workoutCreateTemplate(input:$input){\n            workout {\n                id\n            }\n            errors {\n                message\n            }\n        }\n    }"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetWorkout($id: ID!) {\n        workout(id: $id) {\n            id\n            name\n            notes\n            exercises {\n                id\n                notes\n                movement {\n                    id\n                    name\n                    description\n                    primaryMuscleGroup\n                    equipmentType\n                    movementType\n                }\n                sets {\n                    id\n                    sequenceNumber\n                    completedReps\n                    minReps\n                    maxReps\n                    weight\n                    duration\n                    setType\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetWorkout($id: ID!) {\n        workout(id: $id) {\n            id\n            name\n            notes\n            exercises {\n                id\n                notes\n                movement {\n                    id\n                    name\n                    description\n                    primaryMuscleGroup\n                    equipmentType\n                    movementType\n                }\n                sets {\n                    id\n                    sequenceNumber\n                    completedReps\n                    minReps\n                    maxReps\n                    weight\n                    duration\n                    setType\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation WorkoutCreateCompleted($input:WorkoutCreateCompletedInput!){\n        workoutCreateCompleted(input:$input){\n            workout {\n                id\n            }\n            errors {\n                message\n            }\n        }\n    }"): (typeof documents)["\n    mutation WorkoutCreateCompleted($input:WorkoutCreateCompletedInput!){\n        workoutCreateCompleted(input:$input){\n            workout {\n                id\n            }\n            errors {\n                message\n            }\n        }\n    }"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query weekInReview {\n        weekInReview {\n            message\n            totalWorkouts\n            totalVolume\n            topMuscleGroup\n            totalCardio\n            favoriteEquipment\n        }\n    }\n"): (typeof documents)["\n    query weekInReview {\n        weekInReview {\n            message\n            totalWorkouts\n            totalVolume\n            topMuscleGroup\n            totalCardio\n            favoriteEquipment\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetWorkouts($startMonth: Decimal, $startYear: Decimal) {\n        workouts(startMonth: $startMonth, startYear: $startYear, template: false) {\n            edges {\n                node {\n                    id\n                    startTime\n                    name\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetWorkouts($startMonth: Decimal, $startYear: Decimal) {\n        workouts(startMonth: $startMonth, startYear: $startYear, template: false) {\n            edges {\n                node {\n                    id\n                    startTime\n                    name\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetExercises($movementId: String, $after: String, $before: String, $count: Int) {\n        exercises(movementId: $movementId, after: $after, before: $before, first: $count) {\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n            edges {\n                node{\n                    id\n                    movement {\n                        name\n                        primaryMuscleGroup\n                        equipmentType\n                        movementType\n                    }\n                    workout {\n                        startTime\n                    }\n                    sets {\n                        id\n                        sequenceNumber\n                        completedReps\n                        weight\n                        duration\n                        oneRepMax\n                        volume\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetExercises($movementId: String, $after: String, $before: String, $count: Int) {\n        exercises(movementId: $movementId, after: $after, before: $before, first: $count) {\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n            edges {\n                node{\n                    id\n                    movement {\n                        name\n                        primaryMuscleGroup\n                        equipmentType\n                        movementType\n                    }\n                    workout {\n                        startTime\n                    }\n                    sets {\n                        id\n                        sequenceNumber\n                        completedReps\n                        weight\n                        duration\n                        oneRepMax\n                        volume\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetMovements(\n        $after: String,\n        $name: String,\n        $count: Int,\n        $equipment: String,\n        $muscle: String) {\n            movements(\n                after: $after,\n                name_Icontains: $name,\n                first: $count,\n                equipmentType: $equipment,\n                primaryMuscleGroup: $muscle) {\n                    edges {\n                        cursor\n                        node {\n                            id\n                            name\n                            description\n                            primaryMuscleGroup\n                            equipmentType\n                            movementType\n                        }\n                    }\n            }\n    }\n"): (typeof documents)["\n    query GetMovements(\n        $after: String,\n        $name: String,\n        $count: Int,\n        $equipment: String,\n        $muscle: String) {\n            movements(\n                after: $after,\n                name_Icontains: $name,\n                first: $count,\n                equipmentType: $equipment,\n                primaryMuscleGroup: $muscle) {\n                    edges {\n                        cursor\n                        node {\n                            id\n                            name\n                            description\n                            primaryMuscleGroup\n                            equipmentType\n                            movementType\n                        }\n                    }\n            }\n    }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;
