# Generated by Django 5.1.4 on 2025-01-11 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                (
                    "primary_muscle_group",
                    models.CharField(
                        choices=[
                            ("Abdominals", "Abdominals"),
                            ("Back", "Back"),
                            ("Biceps", "Biceps"),
                            ("Calf", "Calf"),
                            ("Chest", "Chest"),
                            ("Forearm", "Forearm"),
                            ("Glutes", "Glutes"),
                            ("Hamstring", "Hamstring"),
                            ("Lats", "Lats"),
                            ("None", "None"),
                            ("Quadriceps", "Quadriceps"),
                            ("Shoulders", "Shoulders"),
                            ("Trapezius", "Trapezius"),
                            ("Triceps", "Triceps"),
                        ],
                        default="Abdominals",
                        max_length=30,
                    ),
                ),
                (
                    "secondary_muscle_group",
                    models.CharField(
                        choices=[
                            ("Abdominals", "Abdominals"),
                            ("Back", "Back"),
                            ("Biceps", "Biceps"),
                            ("Calf", "Calf"),
                            ("Chest", "Chest"),
                            ("Forearm", "Forearm"),
                            ("Glutes", "Glutes"),
                            ("Hamstring", "Hamstring"),
                            ("Lats", "Lats"),
                            ("None", "None"),
                            ("Quadriceps", "Quadriceps"),
                            ("Shoulders", "Shoulders"),
                            ("Trapezius", "Trapezius"),
                            ("Triceps", "Triceps"),
                        ],
                        default="None",
                        max_length=30,
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("Barbell", "Barbell"),
                            ("Body Only", "Body Only"),
                            ("Cable", "Cable"),
                            ("Dumbbell", "Dumbbell"),
                            ("Exercise Ball", "Exercise Ball"),
                            ("EZ-Curl Bar", "EZ-Curl Bar"),
                            ("Kettlebell", "Kettlebell"),
                            ("Machine", "Machine"),
                            ("Medicine Ball", "Medicine Ball"),
                            ("None", "None"),
                            ("Resistence Bands", "Resistence Bands"),
                        ],
                        default="None",
                        max_length=30,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("Cardio", "Cardio"),
                            ("Plyometrics", "Plyometrics"),
                            ("Strength", "Strength"),
                            ("Stretching", "Stretching"),
                        ],
                        default="Strength",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("intensity", models.IntegerField(default=0)),
                ("notes", models.CharField(max_length=500)),
                ("movement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.movement")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("stop_time", models.DateTimeField(auto_now_add=True)),
                ("template", models.BooleanField(default=False)),
                ("notes", models.CharField(max_length=500)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("sequence_number", models.IntegerField(default=1)),
                ("completed_reps", models.IntegerField(default=0)),
                ("min_reps", models.IntegerField(default=0)),
                ("max_reps", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
                ("duration", models.CharField(blank=True, max_length=20)),
                (
                    "set_type",
                    models.CharField(
                        choices=[
                            ("Drop Set", "Drop Set"),
                            ("Rest Pause Set", "Rest Pause Set"),
                            ("Standard Set", "Standard Set"),
                        ],
                        default="Standard Set",
                        max_length=30,
                    ),
                ),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.exercise")),
                (
                    "parent_set",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.set"),
                ),
                ("workout", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.workout")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
