# Generated by Django 5.1.4 on 2025-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                (
                    "primary_muscle_group",
                    models.CharField(
                        choices=[
                            ("Abdominals", "Abdominals"),
                            ("Back", "Back"),
                            ("Biceps", "Biceps"),
                            ("Calf", "Calf"),
                            ("Chest", "Chest"),
                            ("Forearm", "Forearm"),
                            ("Glutes", "Glutes"),
                            ("Hamstring", "Hamstring"),
                            ("Lats", "Lats"),
                            ("Quadriceps", "Quadriceps"),
                            ("Shoulders", "Shoulders"),
                            ("Trapezius", "Trapezius"),
                            ("Triceps", "Triceps"),
                        ],
                        default="Abdominals",
                        max_length=30,
                    ),
                ),
                (
                    "secondary_muscle_group",
                    models.CharField(
                        choices=[
                            ("Abdominals", "Abdominals"),
                            ("Back", "Back"),
                            ("Biceps", "Biceps"),
                            ("Calf", "Calf"),
                            ("Chest", "Chest"),
                            ("Forearm", "Forearm"),
                            ("Glutes", "Glutes"),
                            ("Hamstring", "Hamstring"),
                            ("Lats", "Lats"),
                            ("Quadriceps", "Quadriceps"),
                            ("Shoulders", "Shoulders"),
                            ("Trapezius", "Trapezius"),
                            ("Triceps", "Triceps"),
                        ],
                        default="Abdominals",
                        max_length=30,
                    ),
                ),
                (
                    "equpment_type",
                    models.CharField(
                        choices=[
                            ("Barbell", "Barbell"),
                            ("Body Only", "Body Only"),
                            ("Cable", "Cable"),
                            ("Dumbbell", "Dumbbell"),
                            ("Exercise Ball", "Exercise Ball"),
                            ("EZ-Curl Bar", "EZ-Curl Bar"),
                            ("Kettlebell", "Kettlebell"),
                            ("Machine", "Machine"),
                            ("Medicine Ball", "Medicine Ball"),
                            ("None", "None"),
                            ("Resistence Bands", "Resistence Bands"),
                        ],
                        default="None",
                        max_length=30,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("Cardio", "Cardio"),
                            ("Plyometrics", "Plyometrics"),
                            ("Strength", "Strength"),
                            ("Stretching", "Stretching"),
                        ],
                        default="Strength",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
