# Generated by Django 5.1.4 on 2025-01-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="set_type",
            field=models.CharField(
                choices=[
                    ("Drop Set", "Drop Set"),
                    ("Rest Pause Set", "Rest Pause Set"),
                    ("Standard Set", "Standard Set"),
                    ("Super Set", "Super Set"),
                ],
                default="Standard Set",
                max_length=30,
            ),
        ),
    ]
