# Generated by Django 5.1.4 on 2025-01-03 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("intensity", models.IntegerField(default=0)),
                ("notes", models.CharField(max_length=500)),
                ("movement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.movement")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("stop_time", models.DateTimeField(auto_now_add=True)),
                ("template", models.BooleanField(default=False)),
                ("notes", models.CharField(max_length=500)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
