# Generated by Django 5.1.4 on 2025-01-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0002_exercise_workout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("sequence_number", models.IntegerField(default=1)),
                ("reps", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
                (
                    "set_type",
                    models.CharField(
                        choices=[
                            ("Drop Set", "Drop Set"),
                            ("Rest Pause Set", "Rest Pause Set"),
                            ("Standard Set", "Standard Set"),
                        ],
                        default="Standard Set",
                        max_length=30,
                    ),
                ),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.exercise")),
                ("workout", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.workout")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
