# Generated by Django 5.1.4 on 2025-01-11 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0002_alter_set_set_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sets", to="AwakenFit.exercise"
            ),
        ),
        migrations.AlterField(
            model_name="set",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sets", to="AwakenFit.workout"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="workouts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
