# Generated by Django 5.1.4 on 2025-01-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0003_alter_set_exercise_alter_set_workout_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="set",
            name="workout",
        ),
        migrations.AddField(
            model_name="exercise",
            name="workout",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="AwakenFit.workout",
            ),
            preserve_default=False,
        ),
    ]
