# Generated by Django 5.1.4 on 2025-01-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0003_set"),
    ]

    operations = [
        migrations.RenameField(
            model_name="set",
            old_name="reps",
            new_name="completed_reps",
        ),
        migrations.AddField(
            model_name="set",
            name="max_reps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="set",
            name="min_reps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="set",
            name="parent_set",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.set"),
            preserve_default=False,
        ),
    ]
