# Generated by Django 5.1.4 on 2025-01-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0004_remove_set_workout_exercise_workout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="parent_set",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.set"
            ),
        ),
    ]
