# Generated by Django 5.1.4 on 2025-02-01 21:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0007_chatlog_delete_aichatlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="parent_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_sets",
                to="AwakenFit.set",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 1, 21, 5, 2, 607701, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="stop_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 1, 21, 5, 2, 607925, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
