# Generated by Django 5.1.4 on 2025-03-01 17:46

import AwakenFit.models.workout
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0008_alter_set_parent_set_alter_workout_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="start_time",
            field=models.DateTimeField(default=AwakenFit.models.workout.current_datetime),
        ),
        migrations.AlterField(
            model_name="workout",
            name="stop_time",
            field=models.DateTimeField(default=AwakenFit.models.workout.current_datetime),
        ),
    ]
