# Generated by Django 5.1.4 on 2025-03-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0009_alter_workout_start_time_alter_workout_stop_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
