# Generated by Django 5.1.4 on 2025-03-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0010_workout_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="notes",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
