# Generated by Django 5.1.4 on 2025-03-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0011_alter_workout_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="notes",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
