# Generated by Django 5.1.4 on 2025-05-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0012_alter_exercise_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="equipment_identifier",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="movement",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("Barbell", "Barbell"),
                    ("Body Only", "Body Only"),
                    ("Cable", "Cable"),
                    ("Dumbbell", "Dumbbell"),
                    ("Exercise Ball", "Exercise Ball"),
                    ("EZ-Curl Bar", "EZ-Curl Bar"),
                    ("Kettlebell", "Kettlebell"),
                    ("Machine", "Machine"),
                    ("Medicine Ball", "Medicine Ball"),
                    ("None", "None"),
                    ("Resistance Bands", "Resistance Bands"),
                ],
                default="None",
                max_length=30,
            ),
        ),
    ]
