# Generated by Django 5.1.4 on 2025-05-21 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0013_set_equipment_identifier_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("Definite", "Definite"), ("Ongoing", "Ongoing")], default="Ongoing", max_length=20
                    ),
                ),
                ("block_size", models.IntegerField(default=7)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkoutDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("sequence_number", models.IntegerField(default=1)),
                ("day_number", models.IntegerField(default=1)),
                (
                    "workout_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_workout",
                        to="AwakenFit.workout",
                    ),
                ),
                (
                    "workout_three",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="third_workout",
                        to="AwakenFit.workout",
                    ),
                ),
                (
                    "workout_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_workout",
                        to="AwakenFit.workout",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="days", to="AwakenFit.workoutplan"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActiveWorkoutPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("day", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.workoutday")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="AwakenFit.workoutplan")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
