# Generated by Django 5.1.4 on 2025-05-21 22:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0014_workoutplan_workoutday_activeworkoutplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="activeworkoutplan",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="workoutday",
            name="workout_one",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_workout",
                to="AwakenFit.workout",
            ),
        ),
        migrations.AlterField(
            model_name="workoutday",
            name="workout_three",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="third_workout",
                to="AwakenFit.workout",
            ),
        ),
        migrations.AlterField(
            model_name="workoutday",
            name="workout_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_workout",
                to="AwakenFit.workout",
            ),
        ),
    ]
