# Generated by Django 5.1.13 on 2025-10-16 08:35

import AwakenFit.models.active_workout_plan
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0015_activeworkoutplan_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="template_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="activeworkoutplan",
            name="start_date",
            field=models.DateField(default=AwakenFit.models.active_workout_plan.today),
        ),
    ]
