# Generated by Django 5.1.13 on 2025-11-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AwakenFit", "0016_workout_template_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutday",
            name="rest_day",
            field=models.BooleanField(default=True),
        ),
    ]
